language: node_js
node_js:
  - "stable"

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot --base-href "https://andrey-zakharov.github.io/factorio-recipes/"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/factorio-recipes
  on:
    branch: master
