language: node_js
node_js:
  - "stable"

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn ng

script:
  - yarn lint
  - yarn build --base-href https://andrey-zakharov.github.io/factorio-recipes/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/factorio-recipes
  on:
    branch: master
